// 语言工具链: 生成 GsmType.ts 类型定义, 并处理构建产物的语言文件.
// 子命令:
//   node tools/localeTools/index.cjs types  从 static/locales/en.json 生成 src/utils/GsmType.ts
//   node tools/localeTools/index.cjs build  处理 build[Ff]/unpacked/locales, 生成 _locales 国际化文件
// 说明: 上游仓库的原始实现未随仓库分发 (被 .gitignore 的 tools/localeTools/* 排除),
// 此文件按 git 历史中的前身工具 (generateGsmType.js, processLocale.js 等) 行为复原.

const { readFileSync, writeFileSync, readdirSync, mkdirSync, existsSync } = require("fs")
const { join, parse } = require("path")
const { env, argv, exit } = require("process")

const PROJECT_ROOT = join(__dirname, "..", "..")

function generateGsmType() {
	const enPath = join(PROJECT_ROOT, "static", "locales", "en.json")
	const gsmPath = join(PROJECT_ROOT, "src", "utils", "GsmType.ts")

	if (!existsSync(enPath)) {
		console.error(`en.json 不存在: ${enPath}`)
		exit(1)
	}

	const data = JSON.parse(readFileSync(enPath, "utf8"))
	let out = "// GENERATED by `npm run gsm` (tools/localeTools types). Do not edit.\n\nexport type Gsm = {"

	const emitKey = (key, value, level) => {
		if (key.startsWith(":") || key.startsWith("!")) return
		const indent = "\t".repeat(level)
		const displayKey = /^[a-zA-Z_]/.test(key) ? key : `"${key}"`
		const isOptional = key.startsWith("_") ? "?" : ""

		// JSDoc 注释使用键自身的字符串值 (多行折叠为单行), 便于阅读; ! 前缀键是给翻译者的说明, 生成时跳过.
		const comment = typeof value === "string" && value.trim() ? value.replace(/\s*\n+\s*/g, " ").trim() : null
		if (comment) out += `\n${indent}/** ${comment} */`

		if (value !== null && typeof value === "object") {
			out += `\n${indent}${displayKey}: {`
			for (const [k, v] of Object.entries(value)) {
				emitKey(k, v, level + 1)
			}
			out += `\n${indent}}`
		} else {
			out += `\n${indent}${displayKey}${isOptional}: ${typeof value}`
		}
	}

	for (const [key, value] of Object.entries(data)) {
		emitKey(key, value, 1)
	}

	out += "\n}\n"
	writeFileSync(gsmPath, out)
	console.log(`已生成 ${gsmPath}`)
}

function stripBangKeys(obj) {
	for (const key of Object.keys(obj)) {
		if (key.startsWith("!")) {
			delete obj[key]
		} else if (obj[key] !== null && typeof obj[key] === "object") {
			stripBangKeys(obj[key])
		}
	}
}

function build() {
	const firefox = env.FIREFOX === "true"
	const localesRoot = join(PROJECT_ROOT, firefox ? "buildFf" : "build", "unpacked", "locales")
	const formalRoot = join(PROJECT_ROOT, firefox ? "buildFf" : "build", "unpacked", "_locales")

	if (!existsSync(localesRoot)) {
		console.error(`locales 目录不存在: ${localesRoot}`)
		exit(1)
	}

	const files = readdirSync(localesRoot).filter((f) => f.endsWith(".json"))
	for (const file of files) {
		const filePath = join(localesRoot, file)
		const localeData = JSON.parse(readFileSync(filePath, "utf8"))
		const language = parse(file).name

		// 顶层 : 前缀键是商店国际化文案, 提取到 _locales/<lang>/messages.json.
		const messages = {}
		for (const key of Object.keys(localeData)) {
			if (key.startsWith(":")) {
				messages[key.slice(1)] = { message: localeData[key] }
				delete localeData[key]
			}
		}

		// 移除翻译者注释键 (! 前缀).
		stripBangKeys(localeData)

		mkdirSync(join(formalRoot, language), { recursive: true })
		writeFileSync(filePath, JSON.stringify(localeData))
		writeFileSync(join(formalRoot, language, "messages.json"), JSON.stringify(messages))
	}
	console.log(`已处理 ${files.length} 个语言文件 -> ${localesRoot}`)
}

const sub = argv[2]
if (sub === "types") {
	generateGsmType()
} else if (sub === "build") {
	build()
} else {
	console.log("用法: node tools/localeTools/index.cjs <build|types>")
	exit(1)
}
